# Change these first
owner: guichevirtual # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Guichê Pass
    url: https://guichepass.com.br/
  - name: Guichê Estrada
    url: https://guichepass.com.br/guiche-estrada
  - name: Guichê PDV
    url: https://pdv.guichepass.com.br/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /statuspage
  logoUrl: https://raw.githubusercontent.com/guichevirtual/statuspage/master/assets/Logo.png
  name: Guichê Pass
  introTitle: "Monitoramento de serviços do guichê pass."
  introMessage: Aqui serão listados problemas, anúncios e avisos relacionados a plataforma.
  favicon: https://guichepass.com.br/images/gpass.ico
  themeUrl: https://gitcdn.link/repo/guichevirtual/statuspage/master/assets/custom.css
  navbar:
    - title: Status
      href: /
    - title: Guichê pass
      href: https://guichepass.com.br/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  activeIncidents: Ocorrências ativas
  allSystemsOperational: Todos sistemas operacionais
  incidentReport: "Ocorrência #$NUMBER →"
  activeIncidentSummary: Aberto em $DATE com $POSTS posts
  incidentTitle: Detalhes da ocorrência $NUMBER
  incidentDetails: Detalhes da ocorrência
  incidentFixed: Arrumado
  incidentOngoing: Em andamento
  incidentOpenedAt: Aberto em
  incidentClosedAt: Fechado em
  incidentSubscribe: Se inscreva para atualizações
  incidentViewOnGitHub: Veja no github
  incidentCommentSummary: Informado em $DATE por $AUTHOR
  incidentBack: ← Voltar para todas ocorrências
  pastIncidents: Ocorrências passadas
  pastIncidentsResolved: Resolvido em $MINUTES minutos com $POSTS posts
  liveStatus: status ao vivo
  overallUptime: "Tempo em operação: $UPTIME"
  overallUptimeTitle: Tempo em operação
  averageResponseTime: "Tempo de resposta médio: $TIMEms"
  averageResponseTimeTitle: Tempo de resposta médio
  sevelDayResponseTime: Tempo de resposta médio - 7 dias
  responseTimeMs: Tempo de resposta (ms)
  up: Operacional
  down: Não operacional
  degraded: Degradado
  ms: ms
  loading: Carregando
  navGitHub: GitHub
  footer: Guichê pass - 2021
  errorTitle: Um erro ocorreu!
  errorIntro: Um erro ocorreu enquanto os dados mais recentes estavam sendo carregados!
  errorText: Você poderá tentar novamente em alguns instantes.
  errorHome: Vá para página principal
  pastScheduledMaintenance: Manutenções agendadas
  scheduledMaintenance: Manutenção agendada
  scheduledMaintenanceSummaryStarted: Iniciado em $DATE por $DURATION minutos
  scheduledMaintenanceSummaryStarts: Início em $DATE por $DURATION minutos
  startedAt: Iniciado em
  startsAt: Início em
  duration: Duração
  durationMin: $DURATION minutos
  incidentCompleted: Completo
  incidentScheduled: Agendado
